spring:
  cloud:
    gateway:
      routes:

        # SBI user service
        - id: sbi-user-service
          uri: http://localhost:8081
          predicates:
            - Path=/me/**
            - Header=X-Bank-Code, SBI

        # HDFC user service
        - id: hdfc-user-service
          uri: http://localhost:8082
          predicates:
            - Path=/me/**
            - Header=X-Bank-Code, HDFC

jwt:
  secret: ThisIsAVeryLongSecretKeyForHS384AlgorithmAtLeast48BytesLong!!!
