spring:
  cloud:
    gateway:
      routes:

        - id: sbi-user-service
          uri: http://localhost:8082   # SBI runs here
          predicates:
            - Path=/me/**
            - BankCode=SBI

        - id: hdfc-user-service
          uri: http://localhost:8081   # HDFC runs here
          predicates:
            - Path=/me/**
            - BankCode=HDFC

jwt:
  secret: ThisIsAVeryLongSecretKeyForHS384AlgorithmAtLeast48BytesLong!!!
